- name: Deploy Application
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Test connection
      ping:

    - name: Include Install Docker role
      include_role:
        name: ansible/roles/docker

    - name: Include Create Network role
      include_role:
        name: ansible/roles/network

    - name: Include Launch Database role
      include_role:
        name: ansible/roles/database

    - name: Include Launch App role
      include_role:
        name: ansible/roles/app

    - name: Include Launch Proxy role
      include_role:
        name: ansible/roles/proxy
