name: Deploy with Ansible

on:
  workflow_run:
    workflows:
      - Build and Publish Docker Images
    types:
      - completed

jobs:
  deploy-application:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Step 2: Set up SSH Key for Ansible
      - name: Configure SSH Key
        run: |
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

      # Step 2: Set up Ansible
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      # Step 3: Run Ansible Playbook
      - name: Deploy Application with Ansible
        run: |
          ansible-playbook  -i ansible/inventories/setup.yml ansible/playbooks/deploy-playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
