name: CI devops 2024
on:
  # Launch the workflow on pushes to main and develop branches
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the GitHub repository
      - uses: actions/checkout@v2.5.0

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Navigate to the 'simple-api' directory and build/test the application using Maven
      - name: Build and test with Maven
        run: |
          cd simple-api
          mvn clean install
